### ISSUE TITLE
Icon in Remove Program

### ISSUE THREAD

**Issue by maisondasilva** [SamuelTulach/VirusTotalUploader#103]
https://jrsoftware.org/ishelp/index.php?topic=setup_setupiconfile

![image](https://user-images.githubusercontent.com/11423362/157341272-79e5b741-311d-460a-bf82-db59c4d32967.png)

and

![image](https://user-images.githubusercontent.com/11423362/157341310-049e6f61-cb41-4443-b190-1c3e77bd49fc.png)

**Comment by tnhung2011** [comment]
**Problem with your [request](https://github.com/SamuelTulach/VirusTotalUploader/pull/104)**
+ Samuel changed to a new installer but forgot to get rid of Inno Setup's file ([ref](https://github.com/SamuelTulach/VirusTotalUploader/issues/83))
  - Because the installer's UI is different compared to Inno Setup.
  - Because the compiled binary contains localization.
  - Because the newest remover does have an icon (in Windows Explorer)
 ![image](https://user-images.githubusercontent.com/89075831/158341548-da61693e-34e8-4519-974b-e10b143f10e6.png)

**New installer issues (?)**
You are right, the remover doesn't contain any image in the Control Panel
![image](https://user-images.githubusercontent.com/89075831/158340702-7134f7f9-a0a6-44d7-b797-b11b2ad7a5d5.png)

**Way to represent**
Fix the `appveyor.yml` file.

**Comment by tnhung2011** [comment]
Or maybe that wasn't important, bugs and languages reporting are more helpful than these little bit of details.

**Comment by maisondasilva** [comment]
Fix in new install version 2.0.

![image](https://user-images.githubusercontent.com/11423362/219901626-54ce4434-88a8-4a51-b712-ed8b20681ce1.png)
