### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by luboq** [SamuelTulach/VirusTotalUploader#4]
Sample file: （sry a little large）
http://caiyun.feixin.10086.cn/sh/6UFIL1y6W8o5_NRI

Reporduce step: 
Right click the sample file - scan with VirusTotal - Uploading... - pops out the error window

Win7x64 + [this version compiled from master branch](https://ci.appveyor.com/project/SamuelTulach/virustotaluploader/build/artifacts)

![](https://i.loli.net/2018/11/10/5be6a3c930c83.png)

**Comment by SamuelTulach** [comment]
I tried to reproduce it and I found, that error pops up when:

- You are not connected to internet or something is blocking connection (error pops up imminiately) 
- You have set invalid API key (error pops up after some time of uploading)

Can you please check that your api key is valid and that you have not entered blank space (for example) at the end of the key? And also please check you connetion.

**Comment by luboq** [comment]
@SamuelTulach I recorded a video: (censored)
The error indeed pops up after some time of uploading ( I remove some unchange frames so it looks imminiately), but the API key is here and no blank space before or after the string.

The problem seems to be related to KEY. Although it is not shown in the video, there is a certain probability that KEY will be lost when I go to SETTING again ( but I cannot find the 100% reproduce steps ). and it's also weird that INI file appear not only in its own program file, but also in the folder of detected files as the video shows.

PS: the path is "d:\Dropbox\Technical_Backup\ProgramFiles.Trust\VirusTotalUploader\VirusTotal Uploader.exe" and no CJK characters in the path

Edit: Deleted video with API key

**Comment by SamuelTulach** [comment]
Dammit. I think I found it! It only happens when you upload file that is too large. I am little bit ashamed, that I haven´t tested this propertly. 

![Visual Studio Debugging Screenshot](https://i.imgur.com/Yfv9Lij.png)

From VirusTotal faq:

What is the maximum file size that can be submitted to VirusTotal?
128MB for the web and email interfaces, **32MB for the API interface by default**. Having said this, should you have a strong and justified need to send big files through the API (even larger than 128MB) you can contact us in order to have access to the big files API call. 

So this error technically means, that you have uploaded file, that is too large and the response in not in JSON format. I have added file size check. You should be able to know if you file is too big or not. Can you 
[try new version again](https://ci.appveyor.com/project/SamuelTulach/virustotaluploader/build/artifacts)?

**Comment by luboq** [comment]
@SamuelTulach Thank you. Just tested the new version and it works very well. This issue is closed.

Just a little suggestion: Since the max file size allowed by the API is 32M, does it make no sense to click OK to continue uploading? Wouldn't the UX be better by clicking OK will open the virustotal webpage ( so users can upload through the webpage ) and clicking No will cancel the upload? anyway thanks:)
