### ISSUE TITLE
[Suggestion] Improve settings window

### ISSUE THREAD

**Issue by TheDirectorX** [SamuelTulach/VirusTotalUploader#46]
- [ ] Display the current **Language** in the **Settings** when opening the window.
![image](https://user-images.githubusercontent.com/43481085/85755010-0133c900-b727-11ea-8511-56f16d30edf1.png)

- [ ] When saving, automatically change the language without restarting the program. 
**OR** create a confirmation window for restarting program to apply the language settings (_but only the language so that when entering the API key there is no confirmation_).

**Comment by SamuelTulach** [comment]
> create a confirmation window for restarting program to apply the language settings (but only the language so that when entering the API key there is no confirmation)

Well... [It's restarting now](https://github.com/SamuelTulach/VirusTotalUploader/commit/9956e6c57cdb55cc8e0e4ac7a922385311e4089d). Sadly can't really change the language without restart, because I would have to either dynamically change the text in the main form again, or reinitialize it (so it's simpler to just restart it). I will also have to make a custom messagebox.
